displayName=Runebuddy
author=blazerwazey
description=Recommends the best training methods and gear upgrades for your account
tags=training,skilling,gear,progress,advisor,recommend,levels,upgrade
version=1.0.0
plugins=com.runebuddy.RunebuddyPlugin
build=standard
